services:
  # A Docker web service
  - type: web
    name: esgi_nodejs
    runtime: node

    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    rootDir: ./
    startCommand: npm start # optional (defaults to Dockerfile command)
    envVars:
      - key: dbName
        value: renderDB
      - key: dbUser
        value: userRender
      - key: dbPwd
        value: passwordRender
      - key: dbHost
        value: postgresDB
