services:
  # A Docker web service
  - type: web
    name: esgi_nodejs
    runtime: node

    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    buildCommand: npm install # optional (defaults to no prebuild)

    startCommand: npm start # optional (defaults to Dockerfile command)
    envVars:
      - key: dbUrl
        fromDatabase:
          name: postgresDB
          property: connectionString
databases:
  - name: postgresDB
    plan: free
    region: frankfurt

